### ISSUE TITLE
Ability to attach old data to update events

### ISSUE THREAD

**Issue by brussell98** [DasWolke/RainCache#15]
Some features of my bot require not only knowing what data has changed, but what it changed from. With the current way `PRESENCE_UPDATE` and `GUILD_MEMBER_UPDATE` events are handled I'm unable to do this. I'm requesting that optional additional handling of update events be added to solve this.

**Comment by DasWolke** [comment]
Being worked on and planned for raincache v0.5.0

**Comment by PapiOphidian** [comment]
This will be included in the next major version of RainCache. I'm currently working on a major upgrade
