### ISSUE TITLE
Disable "subcaches"

### ISSUE THREAD

**Issue by AFink** [DasWolke/RainCache#23]
Hi, thank you for your awesome lib. I am currently using it with the blacklist on the structures, which is working really well :D

Well, would it be possible to implement a way to disable the subcaches for e.g. the guild voice_states or presences.

It would also be awesome if the user could decide if a guild should have its features cached or not ;).

Thank you in advance.

I would be availlable to work on the topic in a PR, if you want :D

**Comment by PapiOphidian** [comment]
For guild voice states, you can disable this being cached by adding VOICE_STATE_UPDATE to the disabledEvents Array in the RainCacheOptions. PRESENCE_UPDATE for guild presences. As for having a guild's features cached or not, you can use the structureDefs.guild to blacklist the features property which should ensure that it does not show up in new cache entries.

**Comment by AFink** [comment]
Well, the problem is, that the features are deleted and can't be cached. -> https://github.com/DasWolke/RainCache/blob/master/src/cache/GuildCache.ts#L116

**Comment by PapiOphidian** [comment]
Ah. I see. Okay. I'll see what I can do about that when I get the next chance

**Comment by AFink** [comment]
Thanks a lot :D

Is there a problem if I would handle threads as channels?

**Comment by PapiOphidian** [comment]
There would be no problem with that considering threads *are* channels

**Comment by PapiOphidian** [comment]
It's been a bit of time. Just letting you know this is still being worked on. I haven't used RainCache personally for a while, so there was a conflict of interest, but I'm working on a major version which should be released as soon as possible
